production:
  solr:
    hostname: localhost
    port: 6136
    log_level: WARNING
    path: /solr/default
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 6136
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 6136
    log_level: WARNING
    path: /solr/test
